server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/file_analysis_db
    username: analysis_user
    password: analysis_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

analysis:
  allowed-formats: pdf,docx,txt
  max-file-size: 1048576

logging:
  level:
    com.cosmoscan: DEBUG
    org.springframework.web: WARN